---
title: "Data Visualization"
author: "Xiaochi"
date: "08/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nycflights13)
library(ggplot2)
library(dplyr)
```

## The grammar of graphics

### Components of the grammar

> A statistical graphic is a mapping of data variables to aesthetic attributes of geometric objects.

1. `data`: the dataset containing the variables of interest.
2. `geom`: the geometric object in question. 
    - This refers to the type of object we can observe in a plot. For example: points, lines, and bars.
3. `aes`: aesthetic attributes of the geometric object. 
    - For example, x/y position, color, shape, and size. 
    - Aesthetic attributes are mapped to variables in the dataset.
4. `facet` breaks up a plot into several plots split by the values of another variable.
5. `position` adjustments for barplots
6. `scales`
7. `coord`

## 5NG#3: Histograms

A histogram is a plot that visualizes the distribution of a numerical value as follows:
1. We first cut up the x-axis into a series of bins, where each bin represents a range of values.
2. For each bin, we count the number of observations that fall in the range corresponding to that bin.
3. Then for each bin, we draw a bar whose height marks the corresponding count.

### Histograms via geom_histogram

