---
title: "Attribute data operations"
author: "Xiaochi"
date: "22/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library(dplyr)
library(stringr) # for working with strings (pattern matching)
library(tidyr) # for unite() and separate()
library(spData)
```

# Vector attribute manipulations

```{r}
methods(class = "sf")
```

```{r}
st_sf(
  data.frame(n = world$name_long), 
  g = world$geom)
```

```{r}
world
```

```{r}
dim(world) # it is a 2 dimensional object, with rows and columns
nrow(world) # how many rows?
ncol(world) # how many columns?
```

```{r}
world_df = st_drop_geometry(world)
class(world_df)
```

## subsetting

```{r}
world[1:6, ] # subset rows by position
world[, 1:3] # subset columns by position
world[, c("name_long", "lifeExp")] # subset columns by name
```

```{r}
sel_area = world$area_km2 < 10000
summary(sel_area) # a logical vector
small_countries = world[sel_area, ]
```

```{r}
small_countries = world[world$area_km2 < 10000, ]
```

```{r}
small_countries = subset(world, area_km2 < 10000)
```

```{r}
world1 = dplyr::select(world, name_long, pop)
names(world1)
```

```{r}
# all columns between name_long and pop (inclusive)
world2 = dplyr::select(world, name_long:pop)
names(world2)
```

```{r}
# all columns except subregion and area_km2 (inclusive)
world3 = dplyr::select(world, -subregion, -area_km2)
names(world3)
```

```{r}
world4 = dplyr::select(world, name_long, population = pop)
names(world4)
```

```{r}
world5 = world[, c("name_long", "pop")] # subset columns by name
names(world5)[names(world5) == "pop"] = "population" # rename column manually
names(world5)
```



```{r}
# create throw-away data frame
d = data.frame(pop = 1:10, area = 1:10)

# return data frame object when selecting a single column
d[, "pop", drop = FALSE] # equivalent to d["pop"]
select(d, pop)

# return a vector when selecting a single column
d[, "pop"]
pull(d, pop)
```

```{r}
# data frame object
world[, "pop"]
# vector objects
world$pop
pull(world, pop)
```

```{r}
slice(world, 3:5)
```

```{r}
# Countries with a life expectancy longer than 82 years
world6 = filter(world, lifeExp > 82)
```

```{r}
world7 = world %>%
  filter(continent == "Asia") %>%
  dplyr::select(name_long, continent) %>%
  slice(1:5)
```

## aggregation

```{r}
world_agg1 = aggregate(pop ~ continent, 
                       FUN = sum, 
                       data = world, 
                       na.rm = TRUE)
class(world_agg1)
```

```{r}
world_agg2 = aggregate(world["pop"], 
                       by = list(world$continent),
                       FUN = sum, 
                       na.rm = TRUE)
class(world_agg2)
```

```{r}
world_agg3 = world %>%
  group_by(continent) %>%
  summarize(pop = sum(pop, na.rm = TRUE))
```

```{r}
world %>% 
  summarize(
    pop = sum(pop, na.rm = TRUE), 
    n = n()
    )
```

```{r}
world %>% 
  dplyr::select(pop, continent) %>% 
  group_by(continent) %>% 
  summarize(pop = sum(pop, na.rm = TRUE), n_countries = n()) %>% 
  top_n(n = 3, wt = pop) %>%
  arrange(desc(pop)) %>%
  st_drop_geometry()
```

```{r}
world %>% 
  dplyr::select(pop, continent) %>% 
  group_by(continent) %>% 
  summarize(pop = sum(pop, na.rm = TRUE), n_countries = n()) %>% 
  arrange(desc(pop)) %>%
  st_drop_geometry()
```

## joining

```{r}
coffee_data
```

```{r}
class(coffee_data["name_long"])
```


```{r}
world
```

```{r}
world_coffee = left_join(world, coffee_data)
```

```{r}
names(world_coffee)
```

```{r}
plot(world_coffee["coffee_production_2017"])
```

```{r}
coffee_renamed = rename(coffee_data, nm = name_long)
```

```{r}
world_coffee2 = left_join(world, coffee_renamed, by = c(name_long = "nm"))
```

```{r}
world_coffee_inner = inner_join(world, coffee_data)
#> Joining, by = "name_long"
nrow(world_coffee_inner)
```

```{r}
setdiff(coffee_data$name_long, world$name_long)
```

```{r}
setdiff(world$name_long, coffee_data$name_long)
```


```{r}
coffee_data %>% 
  filter(name_long == "Congo, Dem. Rep. of")
```

```{r}
coffee_data %>% 
  filter(name_long == "Others")
```

```{r}
str_subset(world$name_long, "Dem*.+Congo")
```

```{r}
coffee_data$name_long[grepl("Congo,", coffee_data$name_long)] = 
  str_subset(world$name_long, "Dem*.+Congo")
world_coffee_match = inner_join(world, coffee_data)
#> Joining, by = "name_long"
nrow(world_coffee_match)
```

```{r}
coffee_world = left_join(coffee_data, world)
class(coffee_world)
```

## Creating attributes and removing spatial information

```{r}
world_new = world # do not overwrite our original data
world_new$pop_dens = world_new$pop / world_new$area_km2
```

```{r}
world %>% 
  mutate(pop_dens = pop / area_km2)
```

```{r}
world %>% 
  transmute(pop_dens = pop / area_km2)
```

```{r}
world_unite = world %>%
  unite("con_reg", continent:region_un, sep = ":", remove = TRUE)
```

```{r}
world_separate = world_unite %>% 
  separate(con_reg, c("continent", "region_un"), sep = ":")
```

```{r}
world %>% 
  rename(name = name_long)
```

```{r error=TRUE}
new_names = c("i", "n", "c", "r", "s", "t", "a", "p", "l", "gP", "geom")
world %>% 
  dplyr::set_names(new_names)
```

```{r}
world_data = world %>% st_drop_geometry()
class(world_data)
```
 
# Manipulating raster objects

```{r}
elev = raster(nrows = 6, ncols = 6, res = 0.5,
              xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
              vals = 1:36)
```

```{r}
grain_order = c("clay", "silt", "sand")
grain_char = sample(grain_order, 36, replace = TRUE)
grain_fact = factor(grain_char, levels = grain_order)
grain = raster(nrows = 6, ncols = 6, res = 0.5, 
               xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
               vals = grain_fact)
```

```{r}
grain[1,1]
```

```{r}
levels(grain)[[1]] = cbind(levels(grain)[[1]], 
                           wetness = c("wet", "moist", "dry"))
levels(grain)
```

```{r}
factorValues(grain, grain[c(1, 11, 35)])
```

## subsetting

```{r}
# row 1, column 1
elev[1, 1]
# cell ID 1
elev[1]
```

```{r}
stack(elev, grain)[1]
```

```{r}
r_stack = stack(elev, grain)
names(r_stack) = c("elev", "grain")
# three ways to extract a layer of a stack
raster::subset(r_stack, "elev")
r_stack[["elev"]]
r_stack$elev
```

```{r}
elev[1, 1] = 0
elev[]
```

```{r}
elev[1, 1:2]
```

## summarizing raster objects

```{r}
summary(elev)
```

```{r}
cellStats(elev, sd)
```

```{r}
summary(brick(elev, grain))
```

```{r}
hist(elev)
boxplot(elev)
density(elev)
```

