---
title: "Ecology"
author: "Xiaochi"
date: "09/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(raster)
library(RQGIS)
library(mlr)
library(dplyr)
library(vegan)
```


## Data and data preparation

```{r}
data("study_area", "random_points", "comm", "dem", "ndvi", package = "RQGIS")
```

```{r}
study_area
```

```{r}
random_points
```

```{r}
comm
```

```{r}
dem
```

```{r}
ndvi
```

```{r}
plot(dem)
plot(study_area, alpha = 0, add = TRUE)
```

```{r}
# get_usage("saga:sagawetnessindex")
```

```{r}
data("ep", package = "spDataLarge")
ep
```

```{r}
random_points[, names(ep)] = raster::extract(ep, random_points)
```

## Reducing dimensionality

```{r}
# presence-absence matrix
pa = decostand(comm, "pa")  # 100 rows (sites), 69 columns (species)
# keep only sites in which at least one species was found
pa = pa[rowSums(pa) != 0, ]  # 84 rows, 69 columns
```

```{r}
set.seed(25072018)
nmds = metaMDS(comm = pa, k = 4, try = 500)
nmds$stress
```

```{r}
elev = dplyr::filter(random_points, id %in% rownames(pa)) %>% 
  dplyr::pull(dem)
# rotating NMDS in accordance with altitude (proxy for humidity)
rotnmds = MDSrotate(nmds, elev)
# extracting the first two axes
sc = scores(rotnmds, choices = 1:2)
# plotting the first axis against altitude
plot(y = sc[, 1], x = elev, xlab = "elevation in m", 
     ylab = "First NMDS axis", cex.lab = 0.8, cex.axis = 0.8)
```

## Modeling the floristic gradient

```{r}
# construct response-predictor matrix
# id- and response variable
rp = data.frame(id = as.numeric(rownames(sc)), sc = sc[, 1])
# join the predictors (dem, ndvi and terrain attributes)
rp = inner_join(random_points, rp, by = "id")
```

```{r}
library("tree")
tree_mo = tree(sc ~ dem, data = rp)
plot(tree_mo)
text(tree_mo, pretty = 0)
```

### mlr building blocks

```{r}
# extract the coordinates into a separate data frame
coords = sf::st_coordinates(rp) %>% 
  as.data.frame() %>%
  rename(x = X, y = Y)

# only keep response and predictors which should be used for the modeling
rp = dplyr::select(rp, -id, -spri) %>%
  st_drop_geometry()
```

```{r}
# create task
task = makeRegrTask(data = rp, 
                    target = "sc", 
                    coordinates = coords)
# learner
lrn_rf = makeLearner(cl = "regr.ranger", predict.type = "response")
```

```{r}
# spatial partitioning
perf_level = makeResampleDesc("SpCV", iters = 5)
# specifying random search
ctrl = makeTuneControlRandom(maxit = 50L)
```

```{r}
# specifying the search space
ps = makeParamSet(
  makeIntegerParam("mtry", lower = 1, upper = ncol(rp) - 1),
  makeNumericParam("sample.fraction", lower = 0.2, upper = 0.9),
  makeIntegerParam("min.node.size", lower = 1, upper = 10)
)
```

```{r}
# hyperparamter tuning
set.seed(02082018)
tune = tuneParams(learner = lrn_rf, 
                  task = task,
                  resampling = perf_level,
                  par.set = ps,
                  control = ctrl, 
                  measures = mlr::rmse)
```

### Predictive mapping

```{r}
# learning using the best hyperparameter combination
lrn_rf = makeLearner(cl = "regr.ranger",
                     predict.type = "response",
                     mtry = tune$x$mtry, 
                     sample.fraction = tune$x$sample.fraction,
                     min.node.size = tune$x$min.node.size)
```

```{r}
# doing the same more elegantly using setHyperPars()
lrn_rf = setHyperPars(
  makeLearner("regr.ranger", predict.type = "response"),
  par.vals = tune$x)
```

```{r}
# train model
model_rf = train(lrn_rf, task)
```

```{r}
# to retrieve the ranger output, run:
mlr::getLearnerModel(model_rf)
```

```{r}
library(ranger)
ranger(sc ~ ., 
       data = rp, 
       mtry = tune$x$mtry, 
       sample.fraction = tune$x$sample.fraction,
       min.node.size = tune$x$min.node.size)
```

```{r}
# convert raster stack into a data frame
new_data = as.data.frame(as.matrix(ep))
# apply the model to the data frame
pred_rf = predict(model_rf, newdata = new_data)
# put the predicted values into a raster
pred = dem
# replace altitudinal values by rf-prediction values
pred[] = pred_rf$data$response
```

