---
title: "R Notebook"
output:
  html_notebook: default
  word_document: default
---

```{r}
library(tidyverse)
library(sf)
library(raster)
library(spData)
library(spDataLarge)
library(lwgeom)

knitr::opts_chunk$set()
```

# Vector Data

## An introduction to simple features

```{r}
names(world)
```

```{r}
world
```

```{r}
plot(world, max.plot = 10)
```

```{r}
summary(world["lifeExp"])
```

```{r}
world$geom[[1]]
```

```{r}
world_mini = world[1:2, 1:3]
world_mini
```

```{r}
library(sp)
world_sp = as(world, Class = "Spatial")
world_sp
world_sf = st_as_sf(world_sp)
world_sf
```

## Basic map making

```{r}
plot(world[3:6])
```

```{r}
plot(world["pop"])
```


```{r}
world_asia <- world %>% 
  filter(continent == "Asia")
world_asia
```

```{r}
asia = st_union(world_asia)
asia
```

```{r}
plot(world["pop"], reset = FALSE)
plot(asia, add = TRUE, col = "red")
```

```{r}
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE)
plot(st_geometry(world_cents), add = TRUE, cex = cex)
```

```{r}
india = world[world$name_long == "India", ]
plot(st_geometry(india), expandBB = c(0, 0.2, 0.1, 1), col = "gray", lwd = 3)
plot(world_asia[0], add = TRUE)
```

## Geometry tyeps

## Simple feature geometries (sfg)



```{r}
st_point(c(5, 2))                 # XY point
st_point(c(5, 2, 3))              # XYZ point
st_point(c(5, 2, 1), dim = "XYM") # XYM point
st_point(c(5, 2, 3, 1))           # XYZM point
```

```{r}
# the rbind function simplifies the creation of matrices

## MULTIPOINT
multipoint_matrix = rbind(c(5, 2), c(1, 3), c(3, 4), c(3, 2))
st_multipoint(multipoint_matrix)

## LINESTRING
linestring_matrix = rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2))
st_linestring(linestring_matrix)
```

```{r}
## POLYGON
polygon_list = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
st_polygon(polygon_list)
```

```{r}
## POLYGON with a hole
polygon_border = rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))
polygon_hole = rbind(c(2, 4), c(3, 4), c(3, 3), c(2, 3), c(2, 4))
polygon_with_hole_list = list(polygon_border, polygon_hole)
st_polygon(polygon_with_hole_list)
```

```{r}
## MULTILINESTRING
multilinestring_list = list(
  rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
  rbind(c(1, 2), c(2, 4))
  )
st_multilinestring((multilinestring_list))
```

```{r}
## MULTIPOLYGON
multipolygon_list = list(
  list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5))),
  list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2)))
  )
st_multipolygon(multipolygon_list)
```

```{r}
## GEOMETRYCOLLECTION
gemetrycollection_list = list(st_multipoint(multipoint_matrix),
                              st_linestring(linestring_matrix))
st_geometrycollection(gemetrycollection_list)
```

## Simple feature columns (sfc)

```{r}
# sfc POINT
point1 = st_point(c(5, 2))
point2 = st_point(c(1, 3))
points_sfc = st_sfc(point1, point2)
points_sfc
```

```{r}
# sfc POLYGON
polygon_list1 = list(rbind(c(1, 5), c(2, 2), c(4, 1), c(4, 4), c(1, 5)))
polygon1 = st_polygon(polygon_list1)

polygon_list2 = list(rbind(c(0, 2), c(1, 2), c(1, 3), c(0, 3), c(0, 2)))
polygon2 = st_polygon(polygon_list2)

polygon_sfc = st_sfc(polygon1, polygon2)
polygon_sfc
```

```{r}
# sfc MULTILINESTRING
multilinestring_list1 = list(
  rbind(c(1, 5), c(4, 4), c(4, 1), c(2, 2), c(3, 2)), 
  rbind(c(1, 2), c(2, 4))
  )
multilinestring1 = st_multilinestring((multilinestring_list1))

multilinestring_list2 = list(
  rbind(c(2, 9), c(7, 9), c(5, 6), c(4, 7), c(2, 7)), 
  rbind(c(1, 7), c(3, 8))
  )
multilinestring2 = st_multilinestring((multilinestring_list2))

multilinestring_sfc = st_sfc(multilinestring1, multilinestring2)
multilinestring_sfc
```

```{r}
# sfc GEOMETRY
point_multilinestring_sfc = st_sfc(point1, multilinestring1)
point_multilinestring_sfc
```

```{r}
points_sfc
```

```{r}
st_crs(points_sfc)
```

```{r}
# EPSG definition
st_sfc(point1, point2, crs = 4326)
```

```{r}
# PROJ4STRING definition
st_sfc(point1, point2, crs = "+proj=longlat +datum=WGS84 +no_defs")
```

## The sf class

```{r}
lnd_point = st_point(c(0.1, 51.5))                 # sfg object
lnd_geom = st_sfc(lnd_point, crs = 4326)           # sfc object
lnd_attrib = data.frame(                           # data.frame object
  name = "London",
  temperature = 25,
  date = as.Date("2017-06-21")
  )
lnd_sf = st_sf(lnd_attrib, geometry = lnd_geom)    # sf object
lnd_sf
```

```{r}
class(lnd_sf)
```

# Raster data

## An introduction to raster

```{r}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath)
new_raster
```

```{r}
dim(new_raster)
```

```{r}
ncell(new_raster)
```

```{r}
res(new_raster)
```

```{r}
extent(new_raster)
```

```{r}
crs(new_raster)
```

```{r}
inMemory(new_raster)
```

## Basic map making

```{r}
plot(new_raster)
```

## Raster clsses

```{r}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
new_raster = raster(raster_filepath)
plot(new_raster)
```

```{r}
raster::writeFormats()
```

```{r}
rgdal::gdalDrivers()
```



```{r}
new_raster2 = raster(nrows = 6, ncols = 6, res = 0.5, 
                     xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
                     vals = 1:36)
plot(new_raster2)
```

```{r}
multi_raster_file = system.file("raster/landsat.tif", package = "spDataLarge")
r_brick = brick(multi_raster_file)
r_brick
```

```{r}
nlayers(r_brick)
```

```{r}
plot(r_brick)
```


```{r}
raster_on_disk = raster(r_brick, layer = 1)
plot(raster_on_disk)
```

```{r}
raster_in_memory = raster(xmn = 301905, xmx = 335745,
                          ymn = 4111245, ymx = 4154085, 
                          res = 30)
values(raster_in_memory) = sample(seq_len(ncell(raster_in_memory)))
crs(raster_in_memory) = crs(raster_on_disk)
plot(raster_in_memory)
```


```{r}
r_stack = stack(raster_in_memory, raster_on_disk)
r_stack
```

```{r}
plot(r_stack)
```


# Coordinate Reference System

## Geographic coordinate system

## Projected coordinate reference systems

## CRS in R

```{r}
rgdal::make_EPSG()
```

```{r}
vector_filepath = system.file("vector/zion.gpkg", package = "spDataLarge")
new_vector = st_read(vector_filepath)
```

```{r}
st_crs(new_vector)
```

```{r}
new_vector = st_set_crs(new_vector, 4326) # set CRS
```

```{r}
projection(new_raster) # get CRS
```

```{r}
projection(new_raster) = "+proj=utm +zone=12 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs" # set CRS
```

```{r}
plot(new_raster)
```

# Units

```{r}
luxembourg = world[world$name_long == "Luxembourg", ]
st_area(luxembourg)
```

```{r}
st_area(luxembourg) / 1000000
```

```{r}
units::set_units(st_area(luxembourg), km^2)
```

```{r}
res(new_raster)
```

```{r}
repr = projectRaster(new_raster, crs = "+init=epsg:26912")
res(repr)
```

