---
title: "Geographic data I/O"
author: "Xiaochi"
date: "14/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(dplyr)
library(spData)
library(tmap)
library(rnaturalearth)
library(raster)
```

# Retrieving open data

```{r}
download.file(url = "http://nrdata.nps.gov/programs/lands/nps_boundary.zip",
              destfile = "nps_boundary.zip")
unzip(zipfile = "nps_boundary.zip")
usa_parks <- st_read(dsn = "/Users/liuxiaochi/Documents/R Code/R-for-Data-Science/scripts/Geocomputation with R/temp/Current_Shapes/Data_Store/06-06-12_Posting/nps_boundary.shp")
```

# Geographic data packages

```{r}
library(rnaturalearth)
usa <- ne_countries(country = "United States of America")
usa_sf <- st_as_sf(usa)
plot(usa_sf)
```

```{r}
library(raster)
worldclim_prec <- getData(name = "worldclim", var = "prec", res = 10)

tm_shape(worldclim_prec$prec1) +
  tm_raster()
```

```{r}
library(osmdata)
parks = opq(bbox = "leeds uk") %>% 
  add_osm_feature(key = "leisure", value = "park") %>% 
  osmdata_sf()

tm_shape(parks$osm_polygons) +
  tm_polygons()
```

```{r}
world2 = spData::world
world3 = st_read(system.file("shapes/world.gpkg", package = "spData"))
```

# Geographic web services

```{r}
base_url = "http://www.fao.org"
endpoint = "/figis/geoserver/wfs"
q = list(request = "GetCapabilities")
res = httr::GET(url = httr::modify_url(base_url, path = endpoint), query = q)
res$url
```

```{r}
txt = httr::content(res, "text")
xml = xml2::read_xml(txt)
xml
```

```{r}
qf = list(request = "GetFeature", typeName = "area:FAO_AREAS")
file = tempfile(fileext = ".gml")
httr::GET(url = base_url, query = qf, httr::write_disk(file))
fao_areas = sf::read_sf(file)
```

```{r}
library(ows4R)
wfs = WFSClient$new("http://www.fao.org/figis/geoserver/wfs",
                      serviceVersion = "1.0.0", logger = "INFO")
fao_areas = wfs$getFeatures("area:FAO_AREAS")
```

# File formats

# Data input

## Vector data

```{r}
st_drivers()
```

```{r}
vector_filepath = system.file("shapes/world.gpkg", package = "spData")
world = st_read(vector_filepath)
```

```{r}
cycle_hire_txt = system.file("misc/cycle_hire_xy.csv", package = "spData")
cycle_hire_xy = st_read(cycle_hire_txt, options = c("X_POSSIBLE_NAMES=X",
                                                    "Y_POSSIBLE_NAMES=Y"))
```

```{r}
world_txt = system.file("misc/world_wkt.csv", package = "spData")
world_wkt = read_sf(world_txt, options = "GEOM_POSSIBLE_NAMES=WKT")
```


```{r}
# the same as
world_wkt = st_read(world_txt, 
                    options = "GEOM_POSSIBLE_NAMES=WKT", 
                    quiet = TRUE, 
                    stringsAsFactors = FALSE, 
                    as_tibble = TRUE)
```

```{r}
world_wkt = st_read(world_txt, 
                    options = "GEOM_POSSIBLE_NAMES=WKT")
```


```{r}
u = "https://developers.google.com/kml/documentation/KML_Samples.kml"
download.file(u, "KML_Samples.kml")
st_layers("KML_Samples.kml")
```

```{r}
kml = read_sf("KML_Samples.kml", layer = "Placemarks")
```

## Raster data

```{r}
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
single_layer = raster(raster_filepath)
plot(single_layer)
```

```{r}
multilayer_filepath = system.file("raster/landsat.tif", package = "spDataLarge")
band1 = raster(multilayer_filepath)
plot(band1)
```

```{r}
band3 = raster(multilayer_filepath, band = 3)
plot(band3)
```

```{r}
multilayer_brick = brick(multilayer_filepath)
plot(multilayer_brick)
```

```{r}
multilayer_stack = stack(multilayer_filepath)
plot(multilayer_stack)
```

# Data output

## Vector data

```{r}
st_write(obj = world, dsn = "world.gpkg")
st_write(obj = world, dsn = "world.gpkg", layer_options = "OVERWRITE=YES")
st_write(obj = world, dsn = "world.gpkg", delete_layer = TRUE)
write_sf(obj = world, dsn = "world.gpkg")
```

```{r}
st_write(cycle_hire_xy, 
         "cycle_hire_xy.csv", 
         layer_options = "GEOMETRY=AS_XY")

st_write(world_wkt, 
         "world_wkt.csv", 
         layer_options = "GEOMETRY=AS_WKT")
```
## Raster data

```{r}
writeRaster(single_layer, filename = "my_raster.tif", datatype = "INT2U")

writeRaster(x = single_layer,
            filename = "my_raster.tif",
            datatype = "INT2U",
            options = c("COMPRESS=DEFLATE"),
            overwrite = TRUE)
```

```{r}
writeFormats()
```

# Visual output

```{r}
png(filename = "lifeExp.png", width = 500, height = 350)
plot(world["lifeExp"])
dev.off()
```

```{r}
library(mapview)
mapview_obj = mapview(world, zcol = "lifeExp", legend = TRUE)
mapshot(mapview_obj, file = "my_interactive_map.jpeg")
```

