---
title: "Making maps with R"
author: "Xiaochi"
date: "12/10/2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
library(sf)
library(raster)
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap) # for static and interactive maps
library(leaflet) # for interactive maps
library(mapview) # for interactive maps
library(ggplot2) # tidyverse data visualization package
library(shiny) # for web applications
```

# Static maps

## tmap basics

```{r}
# Add fill layer to nz shape
tm_shape(nz) +
  tm_fill() 
```

```{r}
# Add border layer to nz shape
tm_shape(nz) +
  tm_borders() 
```

```{r}
# Add fill and border layers to nz shape
tm_shape(nz) +
  tm_fill() +
  tm_borders() 
```


```{r}
qtm(nz)
```

```{r}
qtm(nz) + qtm(nz_height)
```

## Map objects

```{r}
map_nz = tm_shape(nz) + tm_polygons()
class(map_nz)
map_nz
```

```{r}
map_nz1 = map_nz +
  tm_shape(nz_elev) + 
  tm_raster(alpha = 0.7)

class(map_nz1)
map_nz1
```

```{r}
nz_water = st_union(nz) %>% 
  st_buffer(22200) %>% 
  st_cast(to = "LINESTRING")

map_nz2 = map_nz1 +
  tm_shape(nz_water) + 
  tm_lines()

map_nz2
```

```{r}
map_nz3 = map_nz2 +
  tm_shape(nz_height) + 
  tm_dots()

map_nz3
```

```{r}
tmap_arrange(map_nz1, map_nz2, map_nz3)
```


```{r}
tm_shape(nz) +
  tm_polygons() +
  tm_shape(nz_elev) +
  tm_raster(alpha = 0.7) +
  tm_shape(nz_water) +
  tm_lines() +
  tm_shape(nz_height) +
  tm_dots()
```

## Aesthetics

```{r}
ma1 = tm_shape(nz) + 
  tm_fill(col = "red")

ma2 = tm_shape(nz) + 
  tm_fill(col = "red", alpha = 0.3)

ma3 = tm_shape(nz) + 
  tm_borders(col = "blue")

ma4 = tm_shape(nz) + 
  tm_borders(lwd = 3)

ma5 = tm_shape(nz) + 
  tm_borders(lty = 2)

ma6 = tm_shape(nz) + 
  tm_fill(col = "red", alpha = 0.3) +
  tm_borders(col = "blue", lwd = 3, lty = 2)

tmap_arrange(ma1, ma2, ma3, ma4, ma5, ma6)
```

```{r}
nz
```

```{r}
plot(st_geometry(nz), col = nz$Land_area)
```

```{r error=TRUE}
tm_shape(nz) +
  tm_fill(col = nz$Land_area)
```


```{r}
tm_shape(nz) +
  tm_fill(col = "Land_area")
```

```{r}
legend_title = expression("Area (km"^2*")")

map_nza = tm_shape(nz) +
  tm_fill(col = "Land_area", title = legend_title) + 
  tm_borders()

map_nza
```

## Color settings

```{r}
tm_shape(nz) + tm_polygons(col = "Median_income")
breaks = c(0, 3, 4, 5) * 10000
tm_shape(nz) + tm_polygons(col = "Median_income", breaks = breaks)
tm_shape(nz) + tm_polygons(col = "Median_income", n = 10)
tm_shape(nz) + tm_polygons(col = "Median_income", palette = "BuGn")
```

```{r}
tm_shape(nz) + tm_polygons(col = "Median_income", style = "pretty")
tm_shape(nz) + tm_polygons(col = "Median_income", style = "equal")
tm_shape(nz) + tm_polygons(col = "Median_income", style = "quantile")
tm_shape(nz) + tm_polygons(col = "Median_income", style = "jenks")
tm_shape(nz) + tm_polygons(col = "Median_income", style = "cont")
tm_shape(nz) + tm_polygons(col = "Median_income", style = "cat")
```

```{r}
tm_shape(nz) + tm_polygons("Population", palette = "Blues")
```

```{r}
tm_shape(nz) + tm_polygons("Population", palette = "YlOrBr")
```

## Layouts

```{r}
map_nz + 
  tm_compass(type = "8star", position = c("left", "top")) +
  tm_scale_bar(breaks = c(0, 100, 200), text.size = 1)
```

```{r}
map_nz + tm_layout(title = "New Zealand")
```

```{r}
map_nz + tm_layout(scale = 5)
```

```{r}
map_nz + tm_layout(bg.color = "lightblue")
```

```{r}
map_nz + tm_layout(frame = FALSE)
```

```{r}
map_nza + tm_style("bw")
map_nza + tm_style("classic")
map_nza + tm_style("cobalt")
map_nza + tm_style("col_blind")
```

## Faceted maps

```{r}
urban_agglomerations
```

```{r}
urb_1970_2030 = urban_agglomerations %>% 
  filter(year %in% c(1970, 1990, 2010, 2030))
urb_1970_2030
```

```{r}
tm_shape(world) +
  tm_polygons() +
  tm_shape(urb_1970_2030) +
  tm_symbols(col = "black", border.col = "white", size = "population_millions") +
  tm_facets(by = "year", nrow = 2, free.coords = FALSE)
```

## Inset maps

```{r}
nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) %>% 
  st_as_sfc()

nz_region
```

```{r}
nz_height_map = tm_shape(nz_elev, bbox = nz_region) +
  tm_raster(style = "cont", palette = "YlGn", legend.show = TRUE) +
  tm_shape(nz_height) + 
  tm_symbols(shape = 2, col = "red", size = 1) +
  tm_scale_bar(position = c("left", "bottom"))

nz_height_map
```

```{r}
nz_map = tm_shape(nz) + tm_polygons() +
  tm_shape(nz_height) + tm_symbols(shape = 2, col = "red", size = 0.1) + 
  tm_shape(nz_region) + tm_borders(lwd = 3) 

nz_map
```

```{r}
library(grid)
nz_height_map
print(nz_map, vp = viewport(0.8, 0.27, width = 0.5, height = 0.5))
```

```{r}
us_states_map = tm_shape(us_states, projection = 2163) + 
  tm_polygons() + 
  tm_layout(frame = FALSE)
us_states_map
```

```{r}
hawaii_map = tm_shape(hawaii) + 
  tm_polygons() + 
  tm_layout(title = "Hawaii", 
            frame = FALSE, 
            bg.color = NA, 
            title.position = c("LEFT", "BOTTOM"))
hawaii_map
```

```{r}
alaska_map = tm_shape(alaska) + 
  tm_polygons() + 
  tm_layout(title = "Alaska", 
            frame = FALSE, 
            bg.color = NA)
alaska_map
```

```{r}
us_states_map
print(hawaii_map, 
      vp = grid::viewport(0.35, 0.1, width = 0.2, height = 0.1))
print(alaska_map, 
      vp = grid::viewport(0.15, 0.15, width = 0.3, height = 0.3))
```

# Animated maps

```{r}
urb_anim = tm_shape(world) + 
  tm_polygons() + 
  tm_shape(urban_agglomerations) + 
  tm_dots(size = "population_millions") +
  tm_facets(along = "year", free.coords = FALSE)

urb_anim
```

```{r}
#tmap_animation(urb_anim, filename = "urb_anim.gif", delay = 25)
tmap::tmap_animation(tm = urb_anim, 
                     filename = "urban-animated-1.gif", 
                     width = 1200, 
                     height = 800,
                     delay = 100)
```

# Interactive maps

```{r}
tmap_mode("view")
map_nz
```

```{r}
map_nz + tm_basemap(server = "OpenTopoMap")
```


```{r}
world_coffee = left_join(world, coffee_data, by = "name_long")
facets = c("coffee_production_2016", "coffee_production_2017")
tm_shape(world_coffee) + 
  tm_polygons(facets) + 
  tm_facets(nrow = 1, sync = TRUE)
```

```{r}
tmap_mode("plot")
```

```{r}
mapview(nz)
```

```{r}
trails %>%
  st_transform(st_crs(franconia)) %>%
  st_intersection(franconia[franconia$district == "Oberfranken", ]) %>%
  st_collection_extract("LINE") %>%
  mapview(color = "red", lwd = 3, layer.name = "trails") +
  mapview(franconia, zcol = "district", burst = TRUE) +
  breweries
```

```{r}
library(mapdeck)

key <- 'pk.eyJ1IjoieGlhb2NoaTc3NyIsImEiOiJjazFwcGZja2gwem9rM25yeWNub3diNXk3In0.IR99S9vpa9ynmsf88rwEgw'

set_token(key)

library(usethis)
edit_r_environ()

mapdeck_tokens()
```

```{r}
crash_data = read.csv("https://git.io/geocompr-mapdeck")
crash_data = na.omit(crash_data)
ms = mapdeck_style("dark")
mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
  add_grid(data = crash_data, 
           lat = "lat", 
           lon = "lng", 
           cell_size = 1000,
           elevation_scale = 50, 
           layer_id = "grid_layer",
           colour_range = viridisLite::plasma(6))
```

```{r}
mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
  add_polygon(data = lnd, layer_id = "polygon_layer")
```


```{r}
pal = colorNumeric("RdYlBu", domain = cycle_hire$nbikes)
leaflet(data = cycle_hire) %>% 
  addProviderTiles(providers$OpenStreetMap.BlackAndWhite) %>% 
  addCircles(col = ~pal(nbikes), opacity = 0.9) %>% 
  addPolygons(data = lnd, fill = FALSE) %>% 
  addLegend(pal = pal, values = ~nbikes) %>% 
  setView(lng = -0.1, 51.5, zoom = 12) %>% 
  addMiniMap()
```

# Mapping applications

```{r}
library(shiny)    # for shiny apps
library(leaflet)  # renderLeaflet function
library(spData)   # loads the world dataset 

ui = fluidPage(
  sliderInput(inputId = "life", 
              "Life expectancy", 
              49, 
              84, 
              value = 80),
  leafletOutput(outputId = "map")
  )

server = function(input, output) {
  output$map = renderLeaflet({
      leaflet() %>% 
        addProviderTiles("OpenStreetMap.BlackAndWhite") %>%
        addPolygons(data = world[world$lifeExp < input$life, ])
      })
}

shinyApp(ui, server)
?shiny
```

## coffeApp

```{r}
library(sf)
library(shiny)
library(spData)
library(leaflet)
library(tidyverse)
```

```{r}
world_coffee = left_join(world, coffee_data)
pal = colorNumeric(palette = "RdYlBu", domain = c(0, 4000))
```


```{r}
ui = fluidPage(
  sidebarPanel(
    sliderInput("range", 
                "Coffee Production", 
                0, 
                4000,
                value = c(1000, 4000), 
                step = 100),
    selectInput("year", 
                "Year", 
                c(2016, 2017)),
    checkboxInput("legend", 
                  "Show legend", 
                  FALSE)),
  mainPanel(
    leafletOutput("map")))

server = function(input, output, session) {
  
  map_centre = st_centroid(world %>% 
                             filter(name_long == "Brazil")) %>%
    st_coordinates()
  
  # This reactive expression returns a character string representing the selected variable
  yr = reactive({
    paste0("coffee_production_", input$year)
  })
  
  # Reactive expression for the data subset to what the user selected
  filteredData = reactive({
    world_coffee$Production = world_coffee[[yr()]]
    filter(world_coffee, Production >= input$range[1] &
                         Production <= input$range[2])
  })
  
  output$map = renderLeaflet({
    # Things that do not change go here:
    leaflet() %>% addTiles() %>%
      setView(lng = map_centre[, "X"], map_centre[, "Y"], zoom = 2)
  })
  
  # Changes to the map performed in an observer
  observe({
    proxy = leafletProxy("map", data = filteredData()) %>% 
      clearShapes()
    # Show or hide legend
    proxy %>% clearControls() %>% addPolygons(fillColor = ~pal(Production))
    if (input$legend) {
      proxy %>% addLegend(position = "bottomright",
                          pal = pal, values = ~Production)
    }
  })
}

shinyApp(ui, server)
```

# Other maping packages

```{r error=TRUE}
g = st_graticule(nz, lon = c(170, 175), lat = c(-45, -40, -35))
plot(nz_water, graticule = g, axes = TRUE, col = "blue")
raster::plot(nz_elev / 1000, add = TRUE)
plot(st_geometry(nz), add = TRUE)
```

```{r}
library(ggplot2)
g1 = ggplot() + 
  geom_sf(data = nz, aes(fill = Median_income)) +
  geom_sf(data = nz_height) +
  scale_x_continuous(breaks = c(170, 175))
g1
```

```{r}
plotly::ggplotly(g1)
```

```{r}
library(cartogram)
nz_carto = cartogram_cont(nz, "Median_income", itermax = 5)
tm_shape(nz_carto) + 
  tm_polygons("Median_income")
```

```{r}
us_states2163 = st_transform(us_states, 2163)

us_states2163_ncont = cartogram_ncont(us_states2163, "total_pop_15")
tm_shape(us_states2163_ncont) + 
  tm_polygons("total_pop_15")
```

```{r}
us_states2163_dorling = cartogram_dorling(us_states2163, "total_pop_15")

tm_shape(us_states2163_dorling) + 
  tm_polygons("total_pop_15")
```

