---
title: "Reprojecting geographic data"
author: "Xiaochi"
date: "19/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(dplyr)
library(spData)
library(spDataLarge)
library(tmap)
```

# Introduction

```{r}
london = data.frame(lon = -0.1, lat = 51.5) %>% 
  st_as_sf(coords = c("lon", "lat"))
st_is_longlat(london)
```
```{r}
tm_shape(london) +
  tm_bubbles()
```


```{r}
london_geo = st_set_crs(london, 4326)
st_is_longlat(london_geo)
```
```{r}
tm_shape(london_geo) +
  tm_bubbles()
```


```{r}
london_buff_no_crs = st_buffer(london, dist = 1)
```

```{r}
tm_shape(london_buff_no_crs) +
  tm_polygons() +
  tm_shape(london) +
  tm_bubbles()
```


```{r}
london_buff = st_buffer(london_geo, dist = 1)
```


```{r}
tm_shape(london_buff) +
  tm_polygons() +
  tm_shape(london_geo) +
  tm_bubbles()
```

```{r}
geosphere::distGeo(c(0, 0), c(1, 0))
```
```{r}
geosphere::distGeo(c(0, 51.5), c(1, 51.5))
```

```{r}
london_proj = data.frame(x = 530000, y = 180000) %>% 
  st_as_sf(coords = 1:2, crs = 27700)
```
```{r}
st_crs(london_proj)
```

```{r}
st_is_longlat(london_proj)
```

```{r}
london_proj_buff = st_buffer(london_proj, 111320)

tm_shape(london_proj_buff) +
  tm_polygons() +
  tm_shape(london_proj) +
  tm_bubbles()
```

# When to reproject?

```{r error=TRUE}
st_distance(london_geo, london_proj)
```

```{r}
london2 = st_transform(london_geo, 27700)
```

```{r}
st_distance(london2, london_proj)
```

# Which CRS to use?

```{r}
lonlat2UTM = function(lonlat) {
  utm = (floor((lonlat[1] + 180) / 6) %% 60) + 1
  if(lonlat[2] > 0) {
    utm + 32600
  } else{
    utm + 32700
  }
}
```

```{r}
epsg_utm_auk = lonlat2UTM(c(174.7, -36.9))
st_crs(epsg_utm_auk)$proj4string
```
```{r}
epsg_utm_lnd = lonlat2UTM(st_coordinates(london))
st_crs(epsg_utm_lnd)$proj4string
```

# Reprojecting vector geometries

```{r}
cycle_hire_osm
```

```{r}
crs_lnd = st_crs(cycle_hire_osm)
```
```{r}
class(crs_lnd)
```

```{r}
crs_lnd$epsg
```
```{r}
tm_shape(cycle_hire_osm) +
  tm_dots()
```

```{r}
cycle_hire_osm_projected = st_transform(cycle_hire_osm, 27700)
```

```{r}
tm_shape(cycle_hire_osm_projected) +
  tm_dots()
```


```{r}
crs_codes = rgdal::make_EPSG()
dplyr::filter(crs_codes, code == 27700)
```

```{r}
st_crs(27700)$proj4string
```

```{r}
st_crs(cycle_hire_osm)
```
# Modifying map projections

```{r}
world_mollweide = st_transform(world, crs = "+proj=moll")
```

```{r}
tm_shape(world_mollweide) +
  tm_polygons()
```

```{r}
st_is_valid(world_mollweide)
```


```{r}
world_wintri = lwgeom::st_transform_proj(world, crs = "+proj=wintri")
```

```{r}
tm_shape(world_wintri) +
  tm_polygons()
```


```{r}
world_laea1 = st_transform(world, 
                           crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=0 +lat_0=0")
```

```{r}
tm_shape(world_laea1) +
  tm_polygons()
```


```{r}
world_laea2 = st_transform(world,
                           crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40")
```

```{r}
tm_shape(world_laea2) +
  tm_polygons()
```



# Reprojecting raster geometries

```{r}
cat_raster = raster(system.file("raster/nlcd2011.tif", package = "spDataLarge"))
crs(cat_raster)
```
```{r}
tm_shape(cat_raster) +
  tm_raster()
```



```{r}
unique(cat_raster)
```

```{r}
wgs84 = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
cat_raster_wgs84 = projectRaster(cat_raster, crs = wgs84, method = "ngb")
```
```{r}
tm_shape(cat_raster_wgs84) +
  tm_raster()
```




```{r}
con_raster = raster(system.file("raster/srtm.tif", package = "spDataLarge"))
crs(con_raster)
```
```{r}
tm_shape(con_raster) +
  tm_raster()
```


```{r}
equalarea = "+proj=laea +lat_0=37.32 +lon_0=-113.04"
con_raster_ea = projectRaster(con_raster, crs = equalarea, method = "bilinear")
crs(con_raster_ea)
```
```{r}
tm_shape(con_raster_ea) +
  tm_raster()
```















# Reprojecting raster geometries

