---
title: "Spatial data operations"
author: "Xiaochi"
date: "23/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(raster)
library(dplyr)
library(spData)
library(tmap)
```

# Vector data

## Spatial subsetting

```{r}
nz
```

```{r}
nz_height
```

```{r}
canterbury = nz %>% filter(Name == "Canterbury")

tm_shape(canterbury) +
  tm_polygons()

canterbury_height = nz_height[canterbury, ]

tm_shape(canterbury) +
  tm_polygons() +
  tm_shape(canterbury_height) +
  tm_dots()
```

```{r}
nz_height[canterbury, , op = st_disjoint]
```

```{r}
nz_height[canterbury, 2, op = st_disjoint]
```

```{r}
sel_sgbp = st_intersects(x = nz_height, y = canterbury)
class(sel_sgbp)
sel_logical = lengths(sel_sgbp) > 0
canterbury_height2 = nz_height[sel_logical, ]
```

```{r}
st_intersects(x = nz_height, y = canterbury, sparse = FALSE)[, 1]
```

```{r}
canterbury_height3 = nz_height %>%
  filter(st_intersects(x = ., y = canterbury, sparse = FALSE))
```




## Topological relations

```{r}
# create a polygon
a_poly = st_polygon(list(rbind(c(-1, -1), c(1, -1), c(1, 1), c(-1, -1))))
a = st_sfc(a_poly)

# create a line
l_line = st_linestring(x = matrix(c(-1, -1, -0.5, 1), ncol = 2))
l = st_sfc(l_line)

# create points
p_matrix = matrix(c(0.5, 1, -1, 0, 0, 1, 0.5, 1), ncol = 2)
p_multi = st_multipoint(x = p_matrix)
p = st_cast(st_sfc(p_multi), "POINT")
```

```{r}
st_intersects(p, a)
```

```{r}
st_intersects(p, a, sparse = FALSE)
```

```{r}
st_disjoint(p, a, sparse = FALSE)
```

```{r}
st_within(p, a, sparse = FALSE)
```

```{r}
st_touches(p, a, sparse = FALSE)
```

```{r}
sel = st_is_within_distance(p, a, dist = 0.9) # can only return a sparse matrix
lengths(sel) > 0
```


## Spatil joining

```{r}
set.seed(2018) # set seed for reproducibility
(bb_world = st_bbox(world)) # the world's bounds
random_df = tibble(
  x = runif(n = 10, min = bb_world[1], max = bb_world[3]),
  y = runif(n = 10, min = bb_world[2], max = bb_world[4])
)
random_points = random_df %>% 
  st_as_sf(coords = c("x", "y")) %>% # set coordinates
  st_set_crs(4326) # set geographic CRS
```

```{r}
world_random = world[random_points, ]

random_joined = st_join(random_points, world["name_long"])
```


## Non-overlapping joins

```{r}
plot(st_geometry(cycle_hire), col = "blue")
plot(st_geometry(cycle_hire_osm), add = TRUE, pch = 3, col = "red")
```

```{r}
any(st_touches(cycle_hire, cycle_hire_osm, sparse = FALSE))
```

```{r}
cycle_hire_P = st_transform(cycle_hire, 27700)
cycle_hire_osm_P = st_transform(cycle_hire_osm, 27700)
sel = st_is_within_distance(cycle_hire_P, cycle_hire_osm_P, dist = 20)
summary(lengths(sel) > 0)
```

```{r}
z = st_join(cycle_hire_P, cycle_hire_osm_P,
            join = st_is_within_distance, dist = 20)
nrow(cycle_hire)
nrow(z)
```

```{r}
z = z %>% 
  group_by(id) %>% 
  summarize(capacity = mean(capacity))
nrow(z) == nrow(cycle_hire)
```

```{r}
plot(cycle_hire_osm["capacity"])
plot(z["capacity"])
```


## Spatial data aggregation

```{r}
nz_avheight = aggregate(x = nz_height, by = nz, FUN = mean)
```

```{r}
nz_avheight2 = nz %>%
  st_join(nz_height) %>%
  group_by(Name) %>%
  summarize(elevation = mean(elevation, na.rm = TRUE))
```

```{r}
agg_aw = st_interpolate_aw(incongruent[, "value"], aggregating_zones,
                           extensive = TRUE)
agg_aw$value
```



## Distance relations

```{r}
nz_heighest = nz_height %>% top_n(n = 1, wt = elevation)
canterbury_centroid = st_centroid(canterbury)
st_distance(nz_heighest, canterbury_centroid)
```

```{r}
co = filter(nz, grepl("Canter|Otag", Name))
st_distance(nz_height[1:3, ], co)
```

```{r}
plot(st_geometry(co)[2])
plot(st_geometry(nz_height)[2:3], add = TRUE)
```


# Raster data

## Spatial subsetting

```{r}
elev = raster(nrows = 6, ncols = 6, res = 0.5,
              xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
              vals = 1:36)
```


```{r}
id = cellFromXY(elev, xy = c(0.1, 0.1))
elev[id]
# the same as
raster::extract(elev, data.frame(x = 0.1, y = 0.1))
```

```{r}
clip = raster(xmn = 0.9, xmx = 1.8, ymn = -0.45, ymx = 0.45,
              res = 0.3, vals = rep(1, 9))
elev[clip]
```

```{r}
elev[1:2, drop = FALSE]    # spatial subsetting with cell IDs
elev[1, 1:2, drop = FALSE] # spatial subsetting by row,column indices
#> class       : RasterLayer 
```

```{r}
# create raster mask
rmask = elev 
values(rmask) = sample(c(NA, TRUE), 36, replace = TRUE)


# spatial subsetting
elev[rmask, drop = FALSE]           # with [ operator
mask(elev, rmask)                   # with mask()
overlay(elev, rmask, fun = "max")   # with overlay
```


## Map algebra

## Local Operations

```{r}
rcl = matrix(c(0, 12, 1, 12, 24, 2, 24, 36, 3), ncol = 3, byrow = TRUE)
recl = reclassify(elev, rcl = rcl)
```

```{r}
elev + elev
elev^2
log(elev)
elev > 5
```


## Focal operations

```{r}
r_focal = focal(elev, w = matrix(1, nrow = 3, ncol = 3), fun = min)
```


## Zonal operations

```{r}
grain_order = c("clay", "silt", "sand")
grain_char = sample(grain_order, 36, replace = TRUE)
grain_fact = factor(grain_char, levels = grain_order)
grain = raster(nrows = 6, ncols = 6, res = 0.5, 
               xmn = -1.5, xmx = 1.5, ymn = -1.5, ymx = 1.5,
               vals = grain_fact)
```

```{r}
levels(grain)
```

```{r}
levels(grain)[[1]] = cbind(levels(grain)[[1]], wetness = c("wet", "moist", "dry"))
levels(grain)
```


```{r}
z = zonal(elev, grain, fun = "mean") %>%
  as.data.frame()
```


## Global operations and distances



## Map algebra counterparts in vector processing

## Merging rasters

```{r}
aut = getData("alt", country = "AUT", mask = TRUE)
ch = getData("alt", country = "CHE", mask = TRUE)
aut_ch = merge(aut, ch)
```





