---
title: "Stochastic gradient boosting"
author: "Xiaochi"
date: "17/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
library(tidyverse)
library(caret)
library(xgboost)
library(mlr)
library(knitr)
```

## XGBOOST

```{r}
# Load the data and remove NAs
data("PimaIndiansDiabetes2", package = "mlbench")
PimaIndiansDiabetes2 <- na.omit(PimaIndiansDiabetes2)

# Split the data into training and test set
set.seed(123)
training.samples <- PimaIndiansDiabetes2$diabetes %>% 
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- PimaIndiansDiabetes2[training.samples, ]
test.data <- PimaIndiansDiabetes2[-training.samples, ]

# Fit the model on the training set
set.seed(123)
model <- train(diabetes ~., data = train.data, method = "xgbTree",
               trControl = trainControl("cv", number = 10))
# Best tuning parameter
model$bestTune

# Make predictions on the test data
predicted.classes <- model %>% 
  predict(test.data)

# Compute model prediction accuracy rate
mean(predicted.classes == test.data$diabetes)

varImp(model)
```

```{r}
# Load the data
data("Boston", package = "MASS")
Boston

# Split the data into training and test set
set.seed(123)
training.samples <- Boston$medv %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data  <- Boston[training.samples, ]
test.data <- Boston[-training.samples, ]

# Fit the model on the training set
set.seed(123)
model <- train(medv ~., data = train.data, method = "xgbTree",
               trControl = trainControl("cv", number = 10))
# Best tuning parameter mtry
model$bestTune
# Make predictions on the test data
predictions <- model %>% 
  predict(test.data)

# Compute the average prediction error RMSE
RMSE(predictions, test.data$medv)
```

## Xgboost using MLR

```{r}
train_orig <- read_csv("../../data/train.csv")
test_orig <- read_csv("../../data/test.csv")

train <- train_orig %>%
  mutate(dataset = "train")

test <- test_orig %>%
  mutate(dataset = "test")

combined <- bind_rows(train, test)

summarizeColumns(combined)

combined <- combined %>%
  select(-c(PassengerId, Name, Ticket, Cabin))

combined <- combined %>%
  mutate_at(
    .vars = vars("Survived", "Pclass", "Sex", "Embarked"),
    .funs = funs(as.factor(.))
  )

# Impute missing values by field type
imp <- impute(combined, classes = list(factor = imputeMode(),
                                       integer = imputeMean(),
                                       numeric = imputeMean()))
combined <- imp$data
# Show column summary
summarizeColumns(combined)
```


```{r}

```



