---
title: "Basic statistics"
author: "Xiaochi"
date: "23/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Student <- c("John Davis", "Angela Williams", "Bullwinkle Moose", "David Jones", "Janice Markhammer", "Cheryl Cushing", "Reuven Ytzrhak", "Greg Knox", "Joel England", "Mary Rayburn")

Math <- c(502, 600, 412, 358, 495, 512, 410, 625, 573, 522)
Science <- c(95, 99, 80, 82, 75, 85, 80, 95, 89, 86)
English <- c(25, 22, 18, 15, 20, 28, 15, 30, 27, 18)

roster <- data.frame(Student, Math, Science, English, stringsAsFactors=FALSE)
```

```{r}
z <- scale(roster[,2:4])
score <- apply(z, 1, mean)
roster <- cbind(roster, score)
```


# Descriptive statistics

```{r}
myvars <- c("mpg", "hp", "wt")
mtcars[myvars]
```

```{r}
summary(mtcars[myvars])
```

```{r}
mystats <- function(x, na.omit=FALSE){
  if (na.omit)
    x <- x[!is.na(x)]
  m <- mean(x)
  n <- length(x)
  s <- sd(x)
  skew <- sum((x-m)^3/s^3)/n
  kurt <- sum((x-m)^4/s^4)/n - 3
  return(c(n=n, mean=m, stdev=s, skew=skew, kurtosis=kurt))
}

myvars <- c("mpg", "hp", "wt")

sapply(mtcars[myvars], mystats)
```

```{r}
library(Hmisc)
myvars <- c("mpg", "hp", "wt")
describe(mtcars[myvars])
```

```{r}
library(pastecs)
myvars <- c("mpg", "hp", "wt")
stat.desc(mtcars[myvars])
```

```{r}
library(psych)
myvars <- c("mpg", "hp", "wt")
describe(mtcars[myvars])
```

```{r}
myvars <- c("mpg", "hp", "wt")

aggregate(mtcars[myvars], by=list(am=mtcars$am), mean)
```


```{r}
aggregate(mtcars[myvars], by=list(am=mtcars$am), sd)
```

```{r}
dstats <- function(x)sapply(x, mystats)
myvars <- c("mpg", "hp", "wt")
by(mtcars[myvars], mtcars$am, dstats)
```

```{r}
library(doBy)
summaryBy(mpg+hp+wt~am, data=mtcars, FUN=mystats)
```

```{r}
library(psych)
myvars <- c("mpg", "hp", "wt")
describeBy(mtcars[myvars], list(am=mtcars$am))
```

# Frequency and contingency tables

```{r}
library(vcd)
Arthritis
```

```{r}
mytable <- with(Arthritis, table(Improved))
mytable
```

```{r}
prop.table(mytable)
```

```{r}
prop.table(mytable)*100
```

```{r}
mytable <- xtabs(~ Treatment+Improved, data=Arthritis)
mytable
```

```{r}
margin.table(mytable, 1)
```

```{r}
prop.table(mytable, 1)
```

```{r}
margin.table(mytable, 2)
```

```{r}
prop.table(mytable, 2)
```

```{r}
prop.table(mytable)
```


```{r}
addmargins(mytable)
```

```{r}
addmargins(prop.table(mytable))
```

```{r}
addmargins(prop.table(mytable, 1), 2)
```

```{r}
addmargins(prop.table(mytable, 2), 1)
```

```{r}
library(gmodels)
CrossTable(Arthritis$Treatment, Arthritis$Improved)
```

```{r}
mytable <- xtabs(~ Treatment+Sex+Improved, data=Arthritis)
mytable
```

```{r}
ftable(mytable)
```

```{r}
margin.table(mytable, 1)
```

```{r}
margin.table(mytable, 2)
```

```{r}
margin.table(mytable, 3)
```

```{r}
margin.table(mytable, c(1, 3))
```

```{r}
ftable(prop.table(mytable, c(1, 2)))
```

```{r}
ftable(addmargins(prop.table(mytable, c(1, 2)), 3))
```

## Tests of independence

```{r}
# stable version on CRAN
install.packages("bookdown")
```

