---
title: "A model workflow"
author: "Xiaochi"
date: "17/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)  # Includes the workflows package
library(tidyverse)

data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

lm_model <- 
  linear_reg() %>% 
  set_engine("lm")
```


## WHERE DOES THE MODEL BEGIN AND END?


## WORKFLOW BASICS

```{r}
lm_wflow <- 
  workflow() %>% 
  add_model(lm_model)
lm_wflow
```


```{r}
lm_wflow <- 
  lm_wflow %>% 
  add_formula(Sale_Price ~ Longitude + Latitude)
lm_wflow
```


```{r}
lm_fit <- fit(lm_wflow, ames_train)
lm_fit
```


```{r}
predict(lm_fit, ames_test %>% slice(1:3))
```


```{r}
lm_fit %>% 
  update_formula(Sale_Price ~ Longitude)
```


## ADDING RAW VARIABLES TO THE workflow()

```{r}
lm_wflow <- 
  lm_wflow %>% 
  remove_formula() %>% 
  add_variables(outcome = Sale_Price, predictors = c(Longitude, Latitude))
lm_wflow
```


```{r}
fit(lm_wflow, ames_train)
```



## HOW DOES A WORKFLOW USE THE FORMULA?


### TREE-BASED MODELS



### SPECIAL FORMULAS AND IN-LINE FUNCTIONS

```{r}
library(lme4)
library(multilevelmod)
library(workflowsets)
library(kableExtra)

lmer(distance ~ Sex + (age | Subject), data = Orthodont)
```



```{r}
library(censored)

parametric_spec <- survival_reg()

parametric_workflow <- 
  workflow() %>% 
  add_variables(outcome = c(fustat, futime), predictors = c(age, rx)) %>% 
  add_model(parametric_spec, 
            formula = Surv(futime, fustat) ~ age + strata(rx))

parametric_fit <- fit(parametric_workflow, data = ovarian)
parametric_fit
```


## CREATING MULTIPLE WORKFLOWS AT ONCE


```{r}
location <- list(
  longitude = Sale_Price ~ Longitude,
  latitude = Sale_Price ~ Latitude,
  coords = Sale_Price ~ Longitude + Latitude,
  neighborhood = Sale_Price ~ Neighborhood
)
```


```{r}
library(workflowsets)
location_models <- workflow_set(preproc = location, models = list(lm = lm_model))
location_models
```

```{r}
location_models$info[[1]]
```


```{r}
location_models <-
   location_models %>%
   mutate(fit = map(info, ~ fit(.x$workflow[[1]], ames_train)))
location_models
```


```{r}
extract_workflow(location_models, id = "coords_lm")
```


## EVALUATING THE TEST SET

```{r}
final_lm_res <- last_fit(lm_wflow, ames_split)
final_lm_res
```

```{r}
fitted_lm_wflow <- extract_workflow(final_lm_res)
fitted_lm_wflow
```

```{r}
collect_metrics(final_lm_res)
```

```{r}
collect_predictions(final_lm_res) %>% slice(1:5)
```



## CHAPTER SUMMARY

```{r}
library(tidymodels)
data(ames)

ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

lm_model <- linear_reg() %>% set_engine("lm")

lm_wflow <- 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_variables(outcome = Sale_Price, predictors = c(Longitude, Latitude))

lm_fit <- fit(lm_wflow, ames_train)
```

```{r}
214 * 5 / 60
```

```{r}
214 * 5
```


```{r}
214 * 4 / 60
```

dimensionality