---
title: "A review of R modeling fundamentals"
author: "Xiaochi"
date: "10/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## AN EXAMPLE

```{r}
data(crickets, package = "modeldata")
crickets

# Plot the temperature on the x-axis, the chirp rate on the y-axis. The plot elements will be colored differently for each species:
ggplot(crickets, aes(x = temp, y = rate, col = species)) + 
  # Plot points for each data point and color by species
  geom_point() + 
  # Show a simple linear model fit created separately for each species:
  geom_smooth(method = lm, se = FALSE) + 
  labs(x = "Temperature (C)", y = "Chirp Rate (per minute)")
```



```{r}
interaction_fit <-  lm(rate ~ (temp + species)^2, data = crickets) 

# To print a short summary of the model:
interaction_fit
```


```{r}
# Place two plots next to one another:
par(mfrow = c(1, 2))

# Show residuals vs predicted values:
plot(interaction_fit, which = 1)

# A normal quantile plot on the residuals:
plot(interaction_fit, which = 2)
```

```{r}
# Fit a reduced model:
main_effect_fit <-  lm(rate ~ temp + species, data = crickets) 

# Compare the two:
anova(main_effect_fit, interaction_fit)
```

```{r}
summary(main_effect_fit)
```

```{r}
new_values <- data.frame(species = "O. exclamationis", temp = 15:20)
predict(main_effect_fit, new_values)
```

## WHAT DOES THE R FORMULA DO?


## WHY TIDINESS IS IMPORTANT FOR MODELING

```{r}
# Add a missing value to the prediction set
new_values$temp[1] <- NA

# The predict method for `lm` defaults to `na.pass`:
predict(main_effect_fit, new_values, na.cation = na.pass)

# Alternatively 
predict(main_effect_fit, new_values, na.action = na.fail)

# Alternatively
predict(main_effect_fit, new_values, na.action = na.omit)
```


```{r}
mtcars %>% select(-mpg)
mtcars$mpg
corr_res <- map(mtcars %>% select(-mpg), cor.test, y = mtcars$mpg)
corr_res

# The first of the results in the vector: 
corr_res[[1]]
```



```{r}
library(broom)

tidy(corr_res[[1]])
```

```{r}
corr_res %>% 
  # Convert each to a tidy format; `map_dfr()` stacks the data frames 
  map_dfr(tidy, .id = "predictor")
```


```{r}
corr_res %>% 
  # Convert each to a tidy format; `map_dfr()` stacks the data frames 
  map_dfr(tidy, .id = "predictor") %>% 
  ggplot(aes(x = fct_reorder(predictor, estimate))) + 
  geom_point(aes(y = estimate)) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .1) +
  labs(x = NULL, y = "Correlation with mpg")
```



## COMBINING BASE R MODELS AND THE TIDYVERSE


```{r}
split_by_species <- 
  crickets %>% 
  group_nest(species)
split_by_species
```

```{r}
model_by_species <- 
  split_by_species %>% 
  mutate(model = map(data, ~ lm(rate ~ temp, data = .x)))
model_by_species
```

```{r}
model_by_species %>% 
  mutate(coef = map(model, tidy)) %>% 
  select(species, coef) %>% 
  unnest(cols = c(coef))
```

