---
title: "A tidyverse primer"
author: "Xiaochi"
date: "09/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
```

## PRINCIPLES

### DESIGN FOR HUMANS



```{r}
mtcars[order(mtcars$gear, mtcars$mpg), ]
arrange(.data = mtcars, gear, mpg)
```


### REUSE EXISTING DATA STRUCTURES


```{r}
boot_samp <- rsample::bootstraps(mtcars, times = 3)
boot_samp
class(boot_samp)
```


### DESIGN FOR THE PIPE AND FUNCTIONAL PROGRAMMING


```{r}
small_mtcars <- arrange(mtcars, gear)
small_mtcars <- slice(small_mtcars, 1:10)

# or more compactly: 
small_mtcars <- slice(arrange(mtcars, gear), 1:10)

mtcars %>% 
  arrange(gear) %>% 
  slice(1:10)
```


```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point() + 
  geom_smooth(method = lm)
```


```{r}
n <- nrow(mtcars)
ratios <- rep(NA_real_, n)
for (car in 1:n) {
  ratios[car] <- log(mtcars$mpg[car]/mtcars$wt[car])
}
ratios
```


```{r}
ratios <- log(mtcars$mpg/mtcars$wt)
ratios
```


```{r}
compute_log_ratio <- function(mpg, wt) {
  log_base <- getOption("log_base", default = exp(1)) # gets external data
  results <- log(mpg/wt, base = log_base)
  print(mean(results))                                # prints to the console
  done <<- TRUE                                       # sets external data
  results
}

compute_log_ratio <- function(mpg, wt, log_base = exp(1)) {
  log(mpg/wt, base = log_base)
}

map(head(mtcars$mpg, 3), sqrt)
map_dbl(head(mtcars$mpg, 3), sqrt)
map2_dbl(mtcars$mpg, mtcars$wt, compute_log_ratio)
map2_dbl(mtcars$mpg, mtcars$wt, ~ log(.x/.y))
```


```{r}
map(head(mtcars$mpg, 3), sqrt)
map_dbl(head(mtcars$mpg, 3), sqrt)
ratios <- map2_dbl(mtcars$mpg, mtcars$wt, compute_log_ratio)
```




```{r}
# Wants valid names:
data.frame(`variable 1` = 1:2, two = 3:4)

# But can be coerced to use them with an extra option:
df <- data.frame(`variable 1` = 1:2, two = 3:4, check.names = FALSE)
df

# tibbles just work:
tbbl <- tibble(`variable 1` = 1:2, two = 3:4)
tbbl

df$tw
tbbl$tw

df[, "two"]
df["two"]
df$two

tbbl[, "two"]
tbbl["two"]
tbbl$two

```

```{r}
library(lubridate)
url <- "http://bit.ly/raw-train-data-csv"

data <- read_csv(url)

# Step 1: Read in the data.
data %>%
  # Step 2: filter columns and rename stationname
  dplyr::select(station = stationname, date, rides) %>% 
  # Step 3: Convert the character date field to a date encoding. Also, put the data in units of 1K rides
  mutate(date = mdy(date), rides = rides / 1000) %>% 
  # Step 4: Summarize the multiple records using the maximum.
  group_by(date, station) %>% 
  summarize(rides = max(rides), .groups = "drop")
```

we can do this kind of analysis if you can finish the discussion of GD.

```{r}
df <- data.frame(x = c(NA, "a-b", "a-d", "b-c", "d-e"))
df

df %>% extract(x, "A")
df %>% extract(x, c("A", "B"), "([[:alnum:]]+)-([[:alnum:]]+)")
df %>% extract(x, c("A", "B"), "([a-d]+)-([a-d]+)")

x <- c("apple", "banana", "pear")
x
str_view(x, "an")
str_view(x, ".a.")

dot <- "\\."
writeLines(dot)
str_view(c("abc", "a.c", "bef"), "a\\.c")
str_view(c("abc", "a.c", "bef"), "a[.]c")
str_view("a\\b", "\\\\")
str_view(c("apple", "banana", "pear"), "^a")
str_view(c("apple", "banana", "pear"), "a$")
str_view(c("apple pie", "apple", "apple cake"), "apple")
str_view(c("apple pie", "apple", "apple cake"), "^apple$")
# Look for a literal character that normally has special meaning in a regex
str_view(c("abc", "a.c", "a*c", "a c"), "a[.]c")
str_view(c("abc", "a.c", "a*c", "a c"), ".[*]c")
str_view(c("abc", "a.c", "a*c", "a c"), "a[ ]")
str_view(c("grey", "gray"), "gr(e|a)y")


x <- "1888 is the longest year in Roman numerals: MDCCCLXXXVIII"
str_view(x, "CC?")
str_view(x, "CC+")
```

