---
title: "Comparing models with resampling"
author: "Xiaochi"
date: "31/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)

data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)


ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)

lm_model <- linear_reg() %>% set_engine("lm")

lm_wflow <- 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(ames_rec)

lm_fit <- fit(lm_wflow, ames_train)




rf_model <- 
  rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("regression")

rf_wflow <- 
  workflow() %>% 
  add_formula(
    Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
      Latitude + Longitude) %>% 
  add_model(rf_model)




set.seed(1001)
ames_folds <- vfold_cv(ames_train, v = 10)

keep_pred <- control_resamples(save_pred = TRUE, save_workflow = TRUE)


set.seed(1003)
rf_res <- rf_wflow %>% fit_resamples(resamples = ames_folds, control = keep_pred)
```






## CREATING MULTIPLE WORKFLOWS AT ONCE (7.5)


```{r}
location <- list(
  longitude = Sale_Price ~ Longitude,
  latitude = Sale_Price ~ Latitude,
  coords = Sale_Price ~ Longitude + Latitude,
  neighborhood = Sale_Price ~ Neighborhood
)
```

```{r}
library(workflowsets)
location_models <- workflow_set(preproc = location, models = list(lm = lm_model))
location_models
```
```{r}
extract_workflow(location_models, id = "coords_lm")
```



```{r}
location_models$option[[1]]
location_models$result[[1]]
```


```{r}
location_models$info[[1]]

location_models %>% 
  mutate(fit = map(info, ~ fit(.x$workflow[[1]], ames_train))) -> location_models
location_models
```

```{r}
location_models$fit[[1]]
```






## CREATING MULTIPLE MODELS WITH WORKFLOW SETS

```{r}
basic_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal_predictors())

interaction_rec <- 
  basic_rec %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) 

spline_rec <- 
  interaction_rec %>% 
  step_ns(Latitude, Longitude, deg_free = 50)
```


```{r}
preproc <- 
  list(basic = basic_rec, 
       interact = interaction_rec, 
       splines = spline_rec
  )

lm_models <- workflow_set(preproc,
                          list(lm = linear_reg()),
                          cross = FALSE)
lm_models
```


```{r}
lm_models <- 
  lm_models %>% 
  workflow_map("fit_resamples", 
               # Options to `fit_resamples()`: 
               resamples = ames_folds, control = keep_pred,
               # Options to `workflow_map()`: 
               seed = 1101, verbose = TRUE)
lm_models
```

```{r}
lm_models$wflow_id
lm_models$info
lm_models$option
lm_models$result
```



```{r}
collect_metrics(lm_models) %>% 
  filter(.metric == "rmse")
```


```{r}
four_models <- 
  as_workflow_set(random_forest = rf_res) %>% 
  bind_rows(lm_models)
four_models
```

```{r}
library(ggrepel)
autoplot(four_models, metric = "rsq") +
  geom_text_repel(aes(label = wflow_id), nudge_x = 1/8, nudge_y = 1/100) +
  theme(legend.position = "none")
```




## COMPARING RESAMPLED PERFORMANCE STATISTICS


```{r}
rsq_indiv_estimates <- 
  collect_metrics(four_models, summarize = FALSE) %>% 
  filter(.metric == "rsq")

rsq_wider <- 
  rsq_indiv_estimates %>% 
  select(wflow_id, .estimate, id) %>% 
  pivot_wider(id_cols = "id", names_from = "wflow_id", values_from = ".estimate")
rsq_wider
```


```{r}
corrr::correlate(rsq_wider %>% select(-id), quiet = TRUE)
```




```{r}
rsq_indiv_estimates %>% 
  mutate(wflow_id = reorder(wflow_id, .estimate)) %>% 
  ggplot(aes(x = wflow_id, y = .estimate, group = id, color = id)) + 
  geom_line(alpha = .5, lwd = 1.25) + 
  theme(legend.position = "none")
```

```{r}
rsq_wider %>% 
  with(cor.test(basic_lm, splines_lm)) %>% 
  tidy() %>% 
  select(estimate, starts_with("conf"))
```














## SIMPLE HYPOTHESIS TESTING METHODS


```{r}
compare_lm <- 
  rsq_wider %>% 
  mutate(difference = splines_lm - basic_lm)
compare_lm
```


```{r}
lm(difference ~ 1, data = compare_lm) %>% 
  tidy(conf.int = TRUE) %>% 
  select(estimate, p.value, starts_with("conf"))
```

```{r}
rsq_wider %>% 
  with(t.test(splines_lm, basic_lm, paired = TRUE)) %>%
  tidy() %>% 
  select(estimate, p.value, starts_with("conf"))
```











## BAYESIAN METHODS

### A RANDOM INTERCEPT MODEL




```{r}
library(tidyposterior)
library(rstanarm)

four_models
```



```{r}
rsq_anova <-
  perf_mod(
    four_models,
    metric = "rsq",
    prior_intercept = rstanarm::student_t(df = 1),
    chains = 4,
    iter = 5000,
    seed = 1102
  )
```

```{r}
model_post <- 
  rsq_anova %>% 
  # Take a random sample from the posterior distribution so set the seed again to be reproducible. 
  tidy(seed = 1103)

model_post
glimpse(model_post)
```


```{r}
model_post %>% 
  mutate(model = forcats::fct_inorder(model)) %>%
  ggplot(aes(x = posterior)) + 
  geom_histogram(bins = 50, col = "white", fill = "blue", alpha = 0.4) + 
  facet_wrap(~ model, ncol = 1) + 
  labs(x = expression(paste("Posterior for mean ", R^2)))
```

```{r}
autoplot(rsq_anova) +
  geom_text_repel(aes(label = workflow), nudge_x = 1/8, nudge_y = 1/100) +
  theme(legend.position = "none")
```


```{r}
rqs_diff <-
  contrast_models(rsq_anova,
                  list_1 = "splines_lm",
                  list_2 = "basic_lm",
                  seed = 1104)

rqs_diff %>% 
  as_tibble() %>% 
  ggplot(aes(x = difference)) + 
  geom_vline(xintercept = 0, lty = 2) + 
  geom_histogram(bins = 50, color = "white", fill = "red", alpha = 0.4)
```

```{r}
summary(rqs_diff) %>% 
  select(-starts_with("pract"))
```


```{r}
summary(rqs_diff, size = 0.02) %>% 
  select(contrast, starts_with("pract"))
```

```{r}
autoplot(rsq_anova, type = "ROPE", size = 0.02) +
  geom_text_repel(aes(label = workflow)) +
  theme(legend.position = "none")
```

### THE EFFECT OF THE AMOUNT OF RESAMPLING




## CHAPTER SUMMARY




