---
title: "Evaluate your model with resampling"
author: "Xiaochi"
date: "16/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels) # for the rsample package, along with the rest of tidymodels
# Helper packages
library(modeldata)  # for the cells data
```


# THE CELL IMAGE DATA

```{r}
data(cells, package = "modeldata")
cells
```
```{r}
cells %>% 
  count(class) %>% 
  mutate(prop = n/sum(n))
```

# DATA SPLITTING

```{r}
set.seed(123)
cell_split <- initial_split(cells %>% select(-case), 
                            strata = class)
cell_train <- training(cell_split)
cell_test  <- testing(cell_split)
```


```{r}
nrow(cell_train)
nrow(cell_train)/nrow(cells)
```


```{r}
# training set proportions by class
cell_train %>% 
  count(class) %>% 
  mutate(prop = n/sum(n))

# test set proportions by class
cell_test %>% 
  count(class) %>% 
  mutate(prop = n/sum(n))
```


# MODELING

```{r}
rf_mod <- 
  rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")
```

```{r}
set.seed(234)
rf_fit <- 
  rf_mod %>% 
  fit(class ~ ., data = cell_train)
rf_fit
```


# ESTIMATING PERFORMANCE

```{r}
predict(rf_fit, cell_train) %>% 
  bind_cols(predict(rf_fit, cell_train, type = "prob")) %>% 
  # Add the true outcome data back in
  bind_cols(cell_train %>% 
              select(class)) -> rf_training_pred
rf_training_pred
```


```{r}
rf_training_pred %>%                # training set predictions
  roc_auc(truth = class, .pred_PS)
```


```{r}
rf_training_pred %>%                # training set predictions
  accuracy(truth = class, .pred_class)
```

```{r}
rf_testing_pred <- 
  predict(rf_fit, cell_test) %>% 
  bind_cols(predict(rf_fit, cell_test, type = "prob")) %>% 
  bind_cols(cell_test %>% select(class))

rf_testing_pred %>%                   # test set predictions
  roc_auc(truth = class, .pred_PS)

rf_testing_pred %>%                   # test set predictions
  accuracy(truth = class, .pred_class)
```

# FIT A MODEL WITH RESAMPLING

```{r}
set.seed(345)
folds <- vfold_cv(cell_train, v = 10)
folds
```


```{r}
folds$splits[[1]]
analysis(folds$splits[[1]])
assessment(folds$splits[[1]])
```


```{r}
rf_wf <- 
  workflow() %>%
  add_model(rf_mod) %>%
  add_formula(class ~ .)

set.seed(456)
rf_fit_rs <- 
  rf_wf %>% 
  fit_resamples(folds)

rf_fit_rs
```

```{r}
collect_metrics(rf_fit_rs)
```

```{r}
rf_testing_pred %>%                   # test set predictions
  accuracy(truth = class, .pred_class)

rf_testing_pred %>%                   # test set predictions
  roc_auc(truth = class, .pred_PS)
```


# Resampling for spatial data

```{r}
library(spatialsample)
data("ames", package = "modeldata")
ames
```

```{r}
set.seed(234)
folds <- spatial_clustering_cv(ames, coords = c("Latitude", "Longitude"), v = 5)
folds
```

```{r}
library(ggplot2)
library(purrr)
library(dplyr)

plot_splits <- function(split) {
    p <- analysis(split) %>%
        mutate(analysis = "Analysis") %>%
        bind_rows(assessment(split) %>%
                    mutate(analysis = "Assessment")) %>%
        ggplot(aes(Longitude, Latitude, color = analysis)) + 
        geom_point(alpha = 0.5) +
        labs(color = NULL)
    print(p)
}

walk(folds$splits, plot_splits)
```

