---
title: "Fitting models with parsnip"
author: "Xiaochi"
date: "17/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
tidymodels_prefer()

data(ames)
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
```






## CREATE A MODEL


```{r}
linear_reg() %>% set_engine("lm")
```

```{r}
linear_reg() %>% set_engine("glmnet") 
```



```{r}
linear_reg() %>% set_engine("stan")
```


```{r}
linear_reg() %>% set_engine("lm") %>% translate()
```

```{r}
linear_reg(penalty = 1) %>% set_engine("glmnet") %>% translate()
```

```{r}
linear_reg() %>% set_engine("stan") %>% translate()
```

```{r}
lm_model <- 
  linear_reg() %>% 
  set_engine("lm")

lm_form_fit <- 
  lm_model %>% 
  # Recall that Sale_Price has been pre-logged
  fit(Sale_Price ~ Longitude + Latitude, data = ames_train)

lm_form_fit
```


```{r}
lm_model <- 
  linear_reg() %>% 
  set_engine("lm")

lm_xy_fit <- 
  lm_model %>% 
  fit_xy(
    x = ames_train %>% select(Longitude, Latitude),
    y = ames_train %>% pull(Sale_Price)
  )

lm_xy_fit
```


```{r}
?rand_forest
```

```{r}
rand_forest(trees = 1000, min_n = 5) %>% 
  set_engine("ranger") %>% 
  set_mode("regression") %>% 
  translate()
```



```{r}
rand_forest(trees = 1000, min_n = 5) %>% 
  set_engine("ranger", verbose = TRUE) %>% 
  set_mode("regression") %>% 
  translate()
```









## USE THE MODEL RESULTS



```{r}
lm_form_fit
```


```{r}
lm_form_fit %>% extract_fit_engine()
```


```{r}
lm_form_fit %>% extract_fit_engine() %>% vcov()
```

```{r}
lm_form_fit %>% 
  extract_fit_engine() %>% 
  summary()
```




```{r}
model_res <- 
  lm_form_fit %>% 
  extract_fit_engine() %>% 
  summary()
model_res
```


```{r}
# The model coefficient table is accessible via the `coef` method.
param_est <- coef(model_res)
param_est
```

```{r}
class(param_est)
```


```{r}
lm_form_fit
```

```{r}
tidy(lm_form_fit)
```




## MAKE PREDICTIONS

```{r}
ames_test_small <- ames_test %>% slice(1:5)
ames_test_small
predict(lm_form_fit, new_data = ames_test_small)
```

```{r}
ames_test_small %>% 
  select(Sale_Price) %>% 
  bind_cols(predict(lm_form_fit, ames_test_small)) %>% 
  # Add 95% prediction intervals to the results:
  bind_cols(predict(lm_form_fit, ames_test_small, type = "pred_int")) 
```

```{r}
tree_model <- 
  decision_tree(min_n = 2) %>% 
  set_engine("rpart") %>% 
  set_mode("regression")

tree_fit <- 
  tree_model %>% 
  fit(Sale_Price ~ Longitude + Latitude, data = ames_train)

ames_test_small %>% 
  select(Sale_Price) %>% 
  bind_cols(predict(tree_fit, ames_test_small))
```



## PARSNIP-EXTENSION PACKAGES



## CREATING MODEL SPECIFICATIONS




## CHAPTER SUMMARY

```{r}
library(tidymodels)
data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

lm_model <- linear_reg() %>% set_engine("lm")
```

