---
title: "Spending our data"
author: "Xiaochi"
date: "14/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
data(ames)
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))
```




## COMMON METHODS FOR SPLITTING DATA


```{r}
# Set the random number stream using `set.seed()` so that the results can be reproduced later. 
set.seed(501)

# Save the split information for an 80/20 split of the data
ames_split <- initial_split(ames, prop = 0.80)
ames_split
```

```{r}
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
```


```{r}
set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

dim(ames_train)
```



## WHAT ABOUT A VALIDATION SET?


## MULTI-LEVEL DATA




## OTHER CONSIDERATIONS FOR A DATA BUDGET


## CHAPTER SUMMARY

```{r}
library(tidymodels)
data(ames)
ames <- ames %>% mutate(Sale_Price = log10(Sale_Price))

set.seed(123)
ames_split <- initial_split(ames, prop = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
```

