---
title: "Writing in the Social Sciences"
author: "Xiaochi"
date: "02/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Macquarie's Definition of the PHD

The Doctor of Philosophy (PhD) is an ungraded degree awarded for research that demonstrates that the candidate has the capacity to conduct research independently, and form a distinct contribution to the knowledge of the subject and to afford evidence of coherence and originality shown either by the discovery of new facts or by the exercise of independent critical power.

* Ultimately, your thesis - as a finished product and as a process - is a piece of writing (made up of many pieces of writing).

* It may also be the most significant piece of writing you will have done by the end of your degree - 75,000 - 100,000 words (PhD),

Mastery isn't simply about the amount of hours of practice. It's also the quality and effectiveness of that practice.

Effective practice is consistent, intensely focused, and targets content or weaknesses that lie at the edge of one's current abilities.

# Process and Product

formal product

* literature review
* a thesis proposal
* discussion section

informal process

* journaling
* note-taking
* mind-mapping
* improvising
* chatting about your research ideas to a friend

These informal processes are just as important in helping you develop a good writing practice. In fact, they are the raw materials for your writing.


## Free Writing

One of the aims of free writing is to cultivate creative thinking and allow you to get started, wherever you are.

1.  What is the first thing that comes to mind when you think of your research?

My research is mainly about investigating the relationship between lead (Pb) contamination and children blood lead level (BLL), which has a serious influence on children health and cognition. Our study area is the Australia's oldest...

2. What matters to you most about your research topic or idea?

Try to use some different, cutting-edge statistical modeling methods, such as machine learning, deep learning, combining with geographic information system techniques, to investigate the problems in Environmental Health and Public Health, to acquire specific and accurate pattern of the influence

3. What do you find most rewarding and/or challenging about writing?

get paper published, drafting an report of my analysis result, better communication with supervisor and others.

challenging: consider how to organize the words, sentence into a smoothed sentenced. Especially when I write the result section, how to describe the result in a easy understand way.


* Free, or informal, writing can be an excellent way to exercise creativity in your research.

* Because the point is to write without any constraints, what is written can often be a valuable resource for self-reflection and emotional resilience.

* Things that you write informally may not appear in their present form in your formal draft, but where before you had a blank page, you now have quite a few paragraphs of writing.

* Initially, the words and sentences you write informally may seem to you to have no value and not lead anywhere, but they are the raw material out of which a piece of writing take shape.

* Repeat these informal writing exercises as often as you like.

* The beauty of free writing is that you can ask yourself questions that matter to you. The only "rule" is that there is no rule - let go of the need to write in, or sound, a particular way. Just relax into the pen/keyboard and write whatever comes to you in that moment. There is no right or wrong - you're simply allowing your thoughts, however disconnected they may seem, to surface.

* Once they're on paper, it's often easier (or even surprising) to make/find the connections between your ideas.

## Writing Habit

* Write at the same time every day. If you have your pick of times, choose the early morning. When you do something at the same time every day, you are more likely to form a habit. If you do it in the morning, you are less likely to let everything else you need to do get in the way.

* Treat your writing as you would any other appointment. Make an appointment with yourself every day to write. Show up to your appointment with yourself and decline any other invitations to do other things during that time.

* Incorporate some accountability. This can be to yourself, where you keep track of your writing on a spreadsheet. But, it is better if you are accountable to someone else, as a bit of peer pressure goes a long way.

* Write towards deadlines. If you don’t have any external deadlines, set deadlines for yourself. Aim to get your article finished by the end of the month. Or, set a deadline for a draft of each book chapter you are writing.

Develop an expectation for yourself that you will write every day. If you want to become a writer, if you want to publish, if you want to finish your dissertation, you have to write. So, expect yourself to write.

## Developing the Writing Habit

It was my practice to be at my table every day at 05:30 a.,.; and it was also my practice to allow myself no mercy.

He considered the task of writing to be "as is his common work to the common laborer. No gigantic efforts will then be necessary."

they way of the writer is to write. Write, publish, repeat every day.

### Getting Started

If it is important, do it every day. Or else not at all.

It is important to first as Why? Why do I write? What do I hope to receive in return for my effeorts? To get the PhD, to be a real international reseracher.

Hobbies that require tools or equipment can never be done consistently enough for me to really excel at them. But my laptop never leaves my side. Having recognized this I resolved years ago that writing would become my craft; it would be the creative outlet that I could return to each day without fail.

Start by considering the Why of things. Any reason is good enough, or even no reason at all. Don't make it into a big deal; nothing wrong with trying something new on for size. But a strong Why - that is what will carry you through the dark days of te dip and help you come out on the other side with a finished piece of work in your hands.

### A Time and Place For Everything

Results come when you work at your craft every day. Consistency is eveything. Those who are the best in the world, at any task, have become so due to a singularity of purpose.

The mornin is whne I write, and the ritual is always the same. I wake up, turn on the coffee, sit down, and begin.

Because of its portability I can do this anywhere; at home or away. Typically I write for 30 to 45 minutes and produce anywhere from 300 to 700 words. Certainly not a prodigal output, but it is enough to ensure a new article is published each week, with another piece or two in the works. Small actions lead to big results. My morning writing time is set in stone, only missed if I have an early flight to catch or jobsite to attend. And then I try to make it up later.

When choosing your time to write it is best to choose one that starts right after you open your eyes in the morning:

* You are more creative upon waking, and your mind is less distracted by external input.

* If left later into the day there will always be something more urgent to push it aside. By doing it first, you ensure it gets done.

* Set your alarm thirty minutes earlier, get to sleep on time, wake up and write.

### Too Small to Fail

Those same lessons will be learned over time through direct experience. And your experience will be similar to that of others. But in the begining there is only one thing that matters; getting words onto page every day.

With writing, as with any new skill, you must take the long view. Focus not on the end result, but on the process. On the daily practice. Each word counts.

### What TO Write?

Writers are readers, and the beginning writer is unconsciously regurgaitating what they have previously read, either in style or in content. There is a lot of that stuff buried inside that needs to be expunged before your authentic voice shines through. The only way to do is to write every day, and finish what you start on a regular basis.

### Overcoming the fear and just going for it.

Sometimes the words come perfectly, sometimes they do not. The only thing that matters is to keep them coming. Don’t treat each word like a diamond, carefully placing them on the page. Rather, think of them like grains of sand on the beach. They are waiting for you there, infinite in number. Use them freely and with no regard to volume. Cast them all over the page and eventually, something brilliant will shine through.

The cure for self-doubt is to write fast, never looking back. When I learned to touch-type back in primary school we were taught to just keep moving; never correct anything until you are done, then go back through the work. I write the same way. What comes forth will never be perfect the first time. Editing styles and needs vary, but it is sure that you will need at least a minor edit before publishing, so don’t let unreasonable fears stop you from getting those words onto the page. There will be time to polish and revise after but the raw material must be there first.

I feel most creative, or inspired, when I am able to do something I'm quite familiar with. For exampl, using R to clean my reserach data, manage them into good format, establish statistical model to extract pattern and analysis the residual, and draw some graphs that are both self-explained and aesthetic.

writing is an experience of your mind.

* wide reading
    * develops your understanding of a feild
    * 

Joseph Harris, Rewriting, 2017

How do you respond to the works of others in a way that is both generous and assertive? How do you make their words part of what you want to say?

1. Coming to terms - "representing an argument"
2. Forwarding - "reading with the author/s"
3. Countering - "reading against the grain"
4. Taking an approach - "developing your position"



# Before writing your manuscript

1. Think about why you want to publish your work - and whether it's publishable


What comes to mind when I think of finding my voice in writing?

my oppinion
evidence
How to express myself confirmatively and concisely. How to organize the structure. How to provide the evidence

* Am I allowed to
    * use personal pronouns?
    * use direct quotations or always paraphrase?
    * Use past or present tense in citing literature?
    * Write in active or passive sentences?
    * Write in long or short sentences?

# Voice As Relationship

Standing on the shoulders of giants - as researchers, we find our voice through the voices of others.

Voice is about showing how your research builds on earlier work, how you locate your perspective in relation to ongoing debates in the field.

Vocation: a calling, a being called in the sense of being called to dedicate one's life and time to a particular profession or practice.

Keith Devlin's Life by the Numbers




A meeting Rstudio Cheif scienctist Hadley Wickham,

Dear Dr. Wickham,

I'm xiaochi from Macquarie University, Australia. I'm a Ph.D. researcher in Environmental Sciences and I'm a huge fan of your work. Your "R for Data Sciences" has entirely changed my research method, equiping me with modernized eReserach technique so that I can conduct my research in a more efficient and reproducible way, which I really appreicate.

I'd like to show you my reserach progress based on your ............

If my thesis was written as a story, what story would it tell?

to investigate the relationship between environmental lead contamination and children blood lead level.

try to develop a regular

writing as architecture

# Structure

start with the familiar. Go from what your readers know to what


# Week 5: Revising, Editing, Proofreading

how have my ideas about my reserach changed over the last few months?

I changd my idea from focusing on studying the methology of machine learning to focusing on the applicaiton of those tehcniques. 






# Writing for Publication Workshops

## Introduction Section
22 July

## Data and Result
24 Sept

* Do you need a figure or a table
  * Which is most appropriate?
  * Use the fewest figures and tables to tell your reserach story
  * Figures and tables should be able to stand on their own
  * Ensure figures and tables have a strong visual impact

* Figure legends & Table titles


* Order of writing
  1. Tables and Figures
  2. Results
  3. Methods
  4. Introduction
  5. Discussion
  6. Abstract

* Order of results is important
  * Better understood if in a certain order

text should highlight important points

How to reivew article

past tense

present tense
modal verbs

1. What do my results say?
The difference of growthlines between 2 groups

2. What do these results mean in their context?
These results mean Aboriginal kids tends to have a higher BLL than Non-Aboriginal Kids

3. 


## Discussion 
15 Oct

Function:to answer the questions posedin the Introduction

1st paragraph
last paragrapha

whta is the aim of your paper?

* Continuity devices
  * Repeat key terms
  * Keep a consistent order
  * Keep a conistent point of view
    * Topic should be the subject of the sentence
    * Sentences with the same topic: same subject
  * keep ideas in parallel form
  * Use this plus summary word ("category term")




## Method Section 
12 Nov

## Abstracts & Titles 
3 Dec

# Grant writing
Ian Pauisen

* Shotgun theory of grant writing

* Understand your audience: 
  * panel
  * the people outside the filed
 
* Capture attention
  * First half page is absolutely critical, don't be too technical
  * Aim, Objective, Background

* Graphic that summarize the grant

* Memorable Title

* Target the grant to the reviewers you want
  * Title
  * First page
  * FORC codes

* You're telling a story
  * background, problem, opportunity, aim

* Grant Aims can be ursued in parallel

* Don't need to reinvent the wheel
  * Get examples of successful grants
 
* Track Record - Even more important than you think it is
  * What you are doing, why you are doing
  * understand what each section of the grant is asking for
  * you need to sell yourself as hard as you can
  * Your track record should tell a story: What you have done, 
  * tell otehr people: you are the first person to do this, you establish this...

* Common Problems
  * Too technical, too much jargon
  * Make sure you answer:
    * Why is this cool and important?
    * Why is this the right team?
    * Why is this important to Australia?/the real world?
  * No typos - make it polished and attractive
  * If it not ready - don't submit it this round

* Get Feedback
  * people from outside filed
  * Non-experts

* Rejoinder - can make a difference

Shotgun theory of grant application
Write your grant at the panel spokesperson
Capture theri attention
Tell a story - right approach, right team, right time
Track record is critical
Get advice/feedback from your mentors, HoD, Faculty research manager, successful grantees

reserach funding and grant opportunities/grant-applications

* Tips for gettign grants
  * Every ategory of grants needs a different approach
  * Apply for as many grants as we possibly can
    * we will never get it if we don't apply for
  * Ask the Grant Library to see mroe examples of successful grant aplicaiton

Followship
* Outstanding research outputs
 * publish high-impact articles
* Excellent communication skills
  * writing skills
  * presentation skills
  * plan ahead for interview: cutting-edge future reserach, interdisciplinary collaborations
* Strong recommendation from PhD supervisor
  * Supervisor: top scientist in the world
  * Strong interpersonal skills
  * Highly self-motivated

# Formatting Thesis in R
Dr. Brendan Lanham

Questions:

1. How to cite/add reference?
2. How to set styles
3. How to cooperate with the supervisor

# Writing Basics

## Week 1

Formal
Straightforward
Clearly Written

write easily, fix it later
simple language can be formal

NP


# Conference Presentation

animation in lists helpful
list main points only

should limit text blocks to two lines

simplify yuor data




